schemes:
  image:
    type: Stream
    prefixes:
      '': ['environment://images', 'system://images/']
  cache:
    type: Stream
    prefixes:
      '': ['cache/tutorials.crabston.ch']
      images: ['images/tutorials.crabston.ch']
  log:
    type: Stream
    prefixes:
      '': ['logs/tutorials.crabston.ch']
  backup:
    type: Stream
    prefixes:
      '': ['backup/tutorials.crabston.ch']

  account:
    type: Stream
    prefixes:
      '': ['user://accounts']
  #'user-data':
  #  type: Stream
  #  prefixes:
  #    '': ['user://data']
  #themes:
  #  type: Stream
  #  prefixes:
  #    '': ['environment://themes', 'user://themes']
  #theme:
  #  type: Stream
  #  prefixes:
  #    '': ['environment://themes']
